FROM php:7.2-fpm-stretch

COPY php.ini /usr/local/etc/php/

RUN apt-get update \
  && apt-get install -y apt-utils \
    curl \
    libmemcached-dev \
    libz-dev \
    libpq-dev \
    libjpeg-dev \
    libpng-dev \
    libfreetype6-dev \
    libssl-dev \
    libmcrypt-dev \
    && docker-php-ext-install mysqli \
    # Install the PHP gd library \
    && docker-php-ext-configure gd \
    --with-jpeg-dir=/usr/lib \
    --with-freetype-dir=/usr/include/freetype2 && \
    docker-php-ext-install gd \
    && rm -rf /var/lib/apt/lists/*