version: '3.3'

services:

    nginx:
        build: ./nginx/
        ports:
            - ${NGINX_PORT}:80
        restart: always
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        depends_on:
            - php
        # working_dir: ${APP_PATH_CONTAINER}

    php:
        build: ./php/
        volumes:
            - ${APP_PATH_HOST}:/var/www/html:cached
        user: ${LOCAL_USER}

    mysql:
        image: mariadb
        ports:
           - ${DB_PORT}:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
            MYSQL_DATABASE: ${DB_NAME}
        volumes:
            - ${DB_PATH_HOST}:/var/lib/mysql
        command: --sql_mode=""

    adminer:
        image: adminer
        restart: always
        ports: 
            - ${ADMINER_PORT}:8080

    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     ports:
    #         - ${ADMINER_PORT}:80
    #     networks:
    #         - database
    #     depends_on:
    #         - mysql
    #     environment:
    #         PMA_HOST: mysql